name = "Vulecc Core"
license = "MIT"
licenselink = "https://github.com/ReverseRoom"
description = "VULECC is the pioneer of the Next-Generation Vulnerability Scanner, empowering companies to offensively exploit their IT assets to find out even the most sophisticated vulnerabilities."

homepage = "https://vulecc.com/"
demosite = "https://vulecc.com/"

tags = ["secure", "faster", "xss scanner", "sqli scanner", "xxe scanner"]
features = ["security aware", "fast by default", "minimum false positives"]

[author]
  name = "Emin Ghuliev"
  homepage = "https://vulecc.com"
